### ISSUE TITLE
Document information architecture (available routes)

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#380]
### Feature description

After discussing our strategy to define the available routes in Saiba and coming to an agreement, we need to document it for future reference.

### Dependencies

Depends on:

- https://github.com/Qiskit/saiba/issues/316

**Comment by abdonrd** [comment]
We can use https://github.com/Qiskit/saiba/issues/316#issuecomment-1320479710 to create this documentation:

### Account

- `/account/learn`: Content explorer
- `/account/teach`: Content management
- `/account/profile`: Profile information

### Public Textbook Courses

- `/course/:courseSlug`: Course home
- `/course/:courseSlug/:unitSlug`: Course unit

### Private Courses

- `/account/teach/course/:courseSlug/edit`: Course management (and its cohorts)
- `/account/teach/course/:courseSlug/cohort/create`: Cohort create
- `/account/teach/course/:courseSlug/cohort/:cohortId/edit`: Cohort edit (right now, this page does not exist)
- `/course/:courseSlug/:unitSlug`: Cohort course unit
- `/cohort/enrollment/:enrollmentCode`: Cohort enrollment
  - Or could be: `/account/learn?cohort-enrollment=enrollmentCode`

### Syllabi

- `/account/teach/syllabus/create`: Syllabus create
- `/account/teach/syllabus/:syllabusCode/edit`: Syllabus management
- `/syllabus/:syllabusCode`: Syllabus home
- `/syllabus/:syllabusCode/:unitSlug`: Syllabus unit

### Authentication

- `/signin`: Public sign in
- `/signin/private-experience`: Private sign in

---

- The `courseSlug` is unique like: `quantum-machine-learning`
  - We can auto-generate it based on the title

- The `unitSlug` is unique like: `introduction-999`
  - `-999` can be anything that makes it unique
  - We can auto-generate it based on the title
  - Note: As the public textbook courses URLs would be affected (because the `-999`), we need to create redirects so as not to lose any already shared/indexed links.

- The `cohortId` is unique auto-generated like: `a98189e2-972c-4ab5-b718-e38b8c14df0f`

- The `syllabusCode` is unique auto-generated like: `TRY-SW8`

- The `enrollmentCode` is unique auto-generated like: `4734b61419fa21d5`
